config/routes.rb
Rails.application.routes.draw do
  root to: 'subs#index'
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]
  resources :posts, except: :index do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :bigint(8)        not null, primary key
#  content           :string           not null
#  author_id         :integer          not null
#  post_id           :integer          not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  parent_comment_id :integer
#

class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :author,
    class_name: :User

  belongs_to :post

  belongs_to :parent_comment,
    class_name: :Comment,
    optional: true

  has_many :child_comments,
    foreign_key: :parent_comment_id,
    class_name: :Comment
end


# _comment partials:
# if child_comments => child_comments.each { |comment| comment.content }
  

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true
  has_many :post_subs

  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User  

  has_many :subs,
    through: :post_subs,
    source: :sub

  has_many :comments
end

app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :bigint(8)        not null, primary key
#  post_id    :integer          not null
#  sub_id     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ApplicationRecord
  validates :post_id, uniqueness: { scope: :sub_id }

  belongs_to :post
  belongs_to :sub
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint(8)        not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, presence: true

  belongs_to :moderator,
    class_name: :User

  has_many :post_subs
  has_many :posts,
    through: :post_subs,
    source: :post
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :username, :session_token, uniqueness: true
  
  attr_reader :password
  after_initialize :ensure_session_token

  has_many :subs,
    foreign_key: :moderator_id
  
  has_many :posts,
    foreign_key: :author_id
  
  has_many :comments,
    foreign_key: :author_id

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user if user && user.is_password?(password)
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def login!(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_login
    redirect_to(new_session_url) unless logged_in?
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login
  
  def new
    @comment = Comment.new
  end

  
  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    # byebug
    if @comment.save
      redirect_to @comment.post # post_url(@comment.post)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def show
    parent_comment = Comment.find(params[:id])
    @comment = Comment.new(parent_comment: parent_comment, post_id: parent_comment.post_id)

  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, except: :show

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.includes(:comments).find(params[:id])
    @all_comments = @post.comments.includes(:child_comments).where(parent_comment_id: nil)
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to subs_url
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids:[])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      login!(@user)
      redirect_to subs_url
    else
      @user = User.new(username: params[:user][:username])
      flash.now[:errors] = ["Couldn't find user by credential"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login, except: [:show, :index]

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator = current_user
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def edit
    @sub = current_user.subs.find(params[:id])
  end

  def update
    @sub = current_user.subs.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def index
    @subs = Sub.all
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new; end

  def create
    user = User.new(user_params)
    if user.save
      login!(user)
      redirect_to subs_url
    else
      flash.now[:errors] = user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<ul>
  <li><%= comment.author.username %>: <a href="<%= comment_url(comment) %>"><%= comment.content %></a></li>
  <%= render comment.child_comments %>
</ul>

app/views/comments/new.html.erb
<h2>Add Comment</h2>

<form action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[post_id]" value="<%=params[:post_id] || @comment.post_id%>">
  <label>Content
    <input type="text" name="comment[content]" value="<%= @comment.content %>">
  </label>

  <input type="submit" value="Create Comment">
</form>

app/views/comments/show.html.erb
<h2>Reply to this comment</h2>

<form action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.parent_comment_id %>">
  
  <label>Content
    <input type="text" name="comment[content]" value="<%= @comment.content %>">
  </label>

  <input type="submit" value="Create Comment">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary text-white">
      <div class="container">
        <a class="navbar-brand" href="<%= root_url %>">RedditClone</a>
        <% if logged_in? %>
          <span>Welcome, <%= current_user.username %>!</span>
          <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="<%= subs_url %>">Subs</a></li>
            <li class="nav-item">
              <form action="<%= session_url %>" method="post">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <input type="hidden" name="_method" value="delete">
                <input type="submit" value="Logout" class="btn btn-danger">
              </form>
            </li>
          </ul>
        <% else %>
          <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="<%= subs_url %>">Subs</a></li>
            <li class="nav-item"><a class="nav-link" href="<%= new_session_url %>">Sign In</a></li>
            <li class="nav-item"><a class="nav-link" href="<%= new_user_url %>">Sign Up</a></li>
          </ul>
        <% end %>
      </div>
    </nav>

    <div class="container">
      <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
          <p class="alert alert-danger"><%= error %></li>
        <% end %>
      <% end %>

      <div class="card">
        <div class="card-body">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
  
</html>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<form action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">

  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <label>URL
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <label>Content
    <textarea name="post[content]">
      <%= @post.content %>
    </textarea>
  </label>

  <ul>
    <input type="hidden" name="post[sub_ids][]" value="">
    <% Sub.all.each do |sub| %>
      <li>
        <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>" <%= 'checked' if @post.sub_ids.include?(sub.id) %> > 
        <%= sub.title %>
      </li>
    <% end %>
  </ul>

  <input type="submit" value="Update Post">
</form>

app/views/posts/new.html.erb
<h2>New Post</h2>

<form action="<%= posts_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="post[sub_id]" value="<%= params[:sub_id]%>">
  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <label>URL
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <label>Content
    <textarea name="post[content]">
      <%= @post.content %>
    </textarea>
  </label>

  <ul>
    <% Sub.all.each do |sub| %>
      <li><input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"> <%= sub.title %></li>
    <% end %>
  </ul>

  <input type="submit" value="Create New Post">
</form>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<a href="#"><%= @post.url %></a><br>
<%= @post.content %>
<b>Create by: </b><%= @post.author.username %>

<div>
  <a href="<%= subs_url %>">Back to subs</a>
</div>

<% if current_user == @post.author %>
  <a href="<%= edit_post_url(@post) %>">
    Edit Post
  </a>
  <form action="<%= post_url(@post) %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="delete">
    <input type="submit" value="Delete Post" class="btn btn-sm btn-danger">
  </form>
<% end %>

<a href="<%= new_post_comment_url(@post) %>">Add Comment</a>


<%= render @all_comments %>

<!-- <%# @post.comments.where(parent_comment_id: nil).each do |comment| %>
  <%#= render 'comment', comment: comment%>
<%# end %> -->

app/views/subs/edit.html.erb
<h2>Edit Sub</h2>

<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">

  <label>Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>

  <input type="submit" value="Update Sub">
</form>

app/views/subs/index.html.erb
<h2>All Subs</h2>
<a href="<%= new_sub_url %>" class="btn btn-sm btn-primary">Make New Sub</a>
<div class="list-group">
  <% @subs.each do |sub| %>
    <a href="<%= sub_url(sub) %>" class="list-group-item list-group-item-action"><%= sub.title %></a>
  <% end %>
</div>

app/views/subs/new.html.erb
<h2>New Sub</h2>

<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="sub[title]">
  </label>

  <label>Description
    <input type="text" name="sub[description]">
  </label>

  <input type="submit" value="Create Sub">
</form>

app/views/subs/show.html.erb
<h2><%= @sub.title %></h2>
<p>Description</p>
<%= @sub.description %>
<br>

<ul>
  <% @sub.posts.each do |post| %>
    <li><a href="<%= post_url(post) %>"><%= post.title %></a></li>
  <% end %>
</ul>

<a href="<%= new_post_url %>">Make New Post!</a>
<a href="<%= subs_url %>">Back to subs</a>
<% if @sub.moderator == current_user %>
  <a href="<%= edit_sub_url(@sub) %>">Edit</a>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Username
    <input type="text" name="user[username]" class="form-control">
  </label>

  <label>Password
    <input type="password" name="user[password]" class="form-control">
  </label>

  <input type="submit" value="Sign Up" class="btn btn-primary">
</form>